export const countriesData = [
    { capital: "Yerevan", description: "Armenia, country of Transcaucasia, lying just south of the great mountain range of the Caucasus and fronting the northwestern extremity of Asia. To the north and east Armenia is bounded by Georgia and Azerbaijan, while its neighbours to the southeast and west are, respectively, Iran and Turkey. Naxçıvan, an exclave of Azerbaijan, borders Armenia to the southwest", id: 1, name: "Armenia", checked: false }, 
    { capital: "Moscow", description: "Russia, country that stretches over a vast expanse of eastern Europe and northern Asia. Once the preeminent republic of the Union of Soviet Socialist Republics (U.S.S.R.; commonly known as the Soviet Union), Russia became an independent country after the dissolution of the Soviet Union in December 1991.", id: 2, name: "Russia", checked: false }, 
    { capital: "Warsaw", description: "Poland, country of central Europe. Poland is located at a geographic crossroads that links the forested lands of northwestern Europe to the sea lanes of the Atlantic Ocean and the fertile plains of the Eurasian frontier. Now bounded by seven nations, Poland has waxed and waned over the centuries, buffeted by the forces of regional history. In the early Middle Ages, Poland’s small principalities and townships were subjugated by successive waves of invaders, from Germans and Balts to Mongols. In the mid-1500s, united Poland was the largest state in Europe and perhaps the continent’s most powerful nation. Yet two and a half centuries later, during the Partitions of Poland (1772–1918), it disappeared, parceled out among the contending empires of Russia, Prussia, and Austria.", id: 3, name: "Poland", checked: false }, 
    { capital: "Paris", description: "France, the largest country in Western Europe, has long been a gateway between the continent's northern and southern regions. Its lengthy borders touch Germany and Belgium in the north; the Atlantic Ocean in the west; the Pyrenees Mountains and Spain in the south.", id: 4, name: "France", checked: false }, 
    { capital: "Berlin", description: "Germany, officially Federal Republic of Germany, German Deutschland or Bundesrepublik Deutschland, country of north-central Europe, traversing the continent’s main physical divisions, from the outer ranges of the Alps northward across the varied landscape of the Central German Uplands and then across the North German Plain.", id: 5, name: "German", checked: false }, 
    { capital: "", description: "", id: 6, name: "Aruba", checked: false }, 
    { capital: "", description: "", id: 7, name: "Afghanistan", checked: false }, 
    { capital: "", description: "", id: 8, name: "Angola", checked: false }, 
    { capital: "", description: "", id: 9, name: "Albania", checked: false }, 
    { capital: "", description: "", id: 10, name: "Andorra", checked: false }, 
    { capital: "", description: "", id: 11, name: "United Arab Emirates", checked: false }, 
    { capital: "", description: "", id: 12, name: "Argentina", checked: false }, 
    { capital: "", description: "", id: 13, name: "American Samoa", checked: false }, 
    { capital: "", description: "", id: 14, name: "Antigua and Barbuda", checked: false }, 
    { capital: "", description: "", id: 15, name: "Australia", checked: false }, 
    { capital: "", description: "", id: 16, name: "Burundi", checked: false }, 
    { capital: "", description: "", id: 17, name: "Belgium", checked: false }, 
    { capital: "", description: "", id: 18, name: "Bangladesh", checked: false }, 
    { capital: "", description: "", id: 19, name: "Benin", checked: false }, 
    { capital: "", description: "", id: 20, name: "Bulgaria", checked: false }, 
    { capital: "", description: "", id: 21, name: "Belarus", checked: false }, 
    { capital: "", description: "", id: 22, name: "Herzegovina", checked: false }, 
    { capital: "", description: "", id: 23, name: "Belize", checked: false }, 
    { capital: "", description: "", id: 24, name: "Bermuda", checked: false }, 
    { capital: "", description: "", id: 25, name: "Bolivia", checked: false }, 
    { capital: "", description: "", id: 26, name: "Bermuda", checked: false }, 
    { capital: "", description: "", id: 27, name: "Canada", checked: false }, 
    { capital: "", description: "", id: 28, name: "Switzerland", checked: false }, 
    { capital: "", description: "", id: 29, name: "Bhutan", checked: false }, 
    { capital: "", description: "", id: 30, name: "Chile", checked: false }
];

